parameters:

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\Adapter\Framework\Http\Controller\:
        resource: '../src/Adapter/Framework/Http/Controller/'
        tags: [ 'controller.service_arguments' ]

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    App\Adapter\Framework\Listener\JsonTransformerExceptionListener:
        tags:
            - { name: kernel.event_listener, event: kernel.exception, method: onKernelException, priority: 100 }
